### ISSUE TITLE
Error: Cannot set property navigator

### ISSUE THREAD

**Issue by bushyice** [node-3d/node-3d#8]
This keeps happening:
```
/home/makano/.local/share/rew/rew.forge3d/app/node_modules/3d-core-raub/js/index.js:91
	global.navigator = navigator;
	                ^

TypeError: Cannot set property navigator of #<Object> which has only a getter
    at _init (/home/makano/.local/share/rew/rew.forge3d/app/node_modules/3d-core-raub/js/index.js:91:19)
    at init (/home/makano/.local/share/rew/rew.forge3d/app/node_modules/3d-core-raub/js/index.js:135:11)
    at createDocument (/home/makano/.local/share/rew/rew.forge3d/app/main.coffee:-3:9)
    at createForge3d (/home/makano/.local/share/rew/rew.forge3d/app/main.coffee:49:21)
    at Forge3D.Weld (/home/makano/.local/share/rew/rew.forge3d/app/main.coffee:86:63)
    at /home/makano/workspace/test-stuff/main.coffee
    at Script.runInContext (node:vm:148:12)
    at Script.runInNewContext (node:vm:153:17)
    at Object.runInNewContext (node:vm:309:38)
    at module.exports.exec (/home/makano/workspace/rew/lib/rew/modules/runtime.js:12:12)
```
It only happens when i require it while in a different path. i am requiring `/home/makano/.local/share/rew/rew.forge3d/app/main.coffee` from `/home/makano/workspace/test-stuff/main.coffee
`

Can you PLEASE wrap this in a try-catch?

**Comment by bushyice** [comment]
Okay, here's what i think we should do. Let's execute most of this in a [`vm`](https://www.npmjs.com/package/vm). Since `three` needs all the browser stuff like `navigator` and `location`, i think it would be safer in it's own context.

**Comment by bushyice** [comment]
![image](https://github.com/node-3d/node-3d/assets/68902447/d503bca1-c8f4-4cb4-9d16-85ce5bf70d5a)
Or do this. Since we're overriding it anyways, it wouldn't make a difference.

**Comment by raub** [comment]
Navigator is needed for some cases where web-libs would use it. Here I think an obvious fix would be to simply check if it already exists. And I wonder why it exists. Last time I'd checked, it was:

```bash
$ node -p "global.navigator"
undefined
```

Are you using some special kind of environment that is not Node and therefore already has `navigator`?
Can you find out why it's already there and what value it holds?

I can't see how using the VM would help. These globals are being set here for web-libs that expect them globally. This module doesn't know when and which libs are going to use the globals. It's like we would have to run the entire thing in a VM, and that's what you can do from the root of your project then.

**Comment by bushyice** [comment]
using the vm, we can run all web libs inside of it, which means it will run separately without fucking up the node's environment. 

And yes i am using a different environment but node modules are still running inside of node. I don't know why this happens. but i will try seeing if i can get a solution, if not i will just include `3d-core-raub`'s js and make adaptations to run in the new environment.

**Comment by bushyice** [comment]
![image](https://github.com/node-3d/node-3d/assets/68902447/fdd6f6bd-8f7d-455e-8dc0-122cf7987205)
Oh i think it exists now, maybe?

**Comment by bushyice** [comment]
i am using node `22.3.0`

**Comment by raub** [comment]
I use Node 20.14.0, so I guess that's a thing in 22. If you wish to use web-libs (such as three.js) inside VM, the whole `3d-core-raub` should just go in there. Web libs and `global` adjustments made by `3d-core-raub` should coexist in the same context because that's the point. If that doesn't make sense, maybe you only need GLFW + WebGL, and not the whole 3d-core environment?

Either way, since 22 adds some random stuff, adjustments should be made for reliability. I will try running node 22 to look for additional issues.

**Comment by bushyice** [comment]
My thought was to make a way to manage the context and run web libs in that context, don't you think having a separate context for web libs is a good choice? we won't have to worry about changing the node's global context.

Also, as far as i have seen, it's all good except the `navigator`. I think they added some APIs in node like `hardwareConcurrency`. Anyways, i think this issue closes here, since we already know the problem, close it when you release the next update.

**Comment by raub** [comment]
Closing this, because `3d-core-raub` works fine with Node 22 now.
